// Portfolio data — single source of truth for RISHI-01
export const PORTFOLIO_DATA = {
  name: 'Rishi Raj Jaiswal',
  title: 'AI/ML Engineer • Full-Stack Developer • Problem Solver',
  tagline: 'Building intelligent systems that learn, adapt, and solve real-world problems.',
  education: {
    degree: 'B.Tech Computer Science Engineering',
    institution: 'MNNIT Allahabad',
    years: '2022 – 2026',
  },
  links: {
    github: 'https://github.com/Rishi-0904',
    linkedin: 'https://linkedin.com/in/rishi-raj-jaiswal',
    leetcode: 'https://leetcode.com/u/Rishi0904/',
    codeforces: 'https://codeforces.com/profile/Rishi0904',
    resume: '/resume.pdf',
    email: 'mailto:rishirajjaiswal0904@gmail.com',
  },
  areas: [
    'Artificial Intelligence',
    'Generative AI',
    'Agentic AI',
    'Machine Learning',
    'Full-Stack Development',
    'Data Structures & Algorithms',
  ],
  skills: {
    ai: [
      { name: 'LangGraph', level: 90 },
      { name: 'LangChain', level: 88 },
      { name: 'RAG', level: 92 },
      { name: 'LLMs', level: 90 },
      { name: 'MCP', level: 80 },
      { name: 'LoRA', level: 78 },
      { name: 'GRPO', level: 75 },
      { name: 'Computer Vision', level: 82 },
      { name: 'TensorFlow', level: 80 },
      { name: 'PyTorch', level: 82 },
      { name: 'Hugging Face', level: 85 },
      { name: 'Embeddings', level: 88 },
      { name: 'Vector Databases', level: 87 },
      { name: 'OCR', level: 80 },
    ],
    backend: [
      { name: 'Node.js', level: 85 },
      { name: 'Express', level: 83 },
      { name: 'FastAPI', level: 90 },
      { name: 'REST APIs', level: 92 },
      { name: 'WebSockets', level: 80 },
      { name: 'Socket.IO', level: 82 },
      { name: 'RabbitMQ', level: 78 },
      { name: 'Redis', level: 75 },
      { name: 'Docker', level: 85 },
      { name: 'PostgreSQL', level: 85 },
      { name: 'MongoDB', level: 80 },
      { name: 'Supabase', level: 82 },
      { name: 'Firebase', level: 78 },
    ],
    frontend: [
      { name: 'React', level: 88 },
      { name: 'Next.js', level: 85 },
      { name: 'TypeScript', level: 85 },
      { name: 'Tailwind CSS', level: 83 },
    ],
    cp: [
      { name: 'C++', level: 90 },
      { name: 'Data Structures', level: 88 },
      { name: 'Algorithms', level: 85 },
      { name: 'Dynamic Programming', level: 82 },
    ],
  },
  projects: [
    {
      id: 'tutor-ai',
      name: 'TutorAI',
      tagline: 'Personalized AI Tutoring & Assessment Platform',
      status: 'completed',
      description:
        'A multi-agent AI tutoring platform that personalizes learning by combining LangGraph orchestration, RAG-powered knowledge retrieval, vision-capable agents, and LoRA-tuned models to adapt to each student\'s learning style.',
      github: 'https://github.com/Rishi-0904',
      demo: '#',
      tech: [
        'LangGraph', 'LangChain', 'RAG', 'MCP', 'LoRA', 'GRPO', 'OCR',
        'pgvector', 'FastAPI', 'React', 'Supabase', 'Docker',
      ],
      architecture: {
        nodes: [
          { id: 'user', label: 'User', desc: 'Student interacts through a React frontend with adaptive UI.' },
          { id: 'orchestrator', label: 'Orchestrator', desc: 'LangGraph orchestrator routes tasks to the right agent based on query type and context.' },
          { id: 'research', label: 'Research Agent', desc: 'Retrieves topic content from the knowledge base using RAG + pgvector similarity search.' },
          { id: 'visual', label: 'Visual Agent', desc: 'Processes diagrams, equations, and images using computer vision + OCR.' },
          { id: 'tutor', label: 'Tutor Agent', desc: 'Generates personalized explanations using a LoRA-finetuned model with GRPO alignment.' },
          { id: 'critic', label: 'Critic Agent', desc: 'Evaluates answers for accuracy and groundedness, preventing hallucinations.' },
          { id: 'answer', label: 'Final Answer', desc: 'Validated, grounded response delivered to the student.' },
        ],
        edges: [
          ['user', 'orchestrator'],
          ['orchestrator', 'research'],
          ['orchestrator', 'visual'],
          ['orchestrator', 'tutor'],
          ['research', 'critic'],
          ['visual', 'critic'],
          ['tutor', 'critic'],
          ['critic', 'answer'],
        ],
      },
    },
    {
      id: 'ringmaster',
      name: "Ringmaster's RoundTable",
      tagline: 'AI-Powered Multi-Agent Travel Planning System',
      status: 'completed',
      description:
        'A real-time multi-agent travel planner that coordinates specialized AI agents for weather, budget, routing, and hotel planning via RabbitMQ message queues and Socket.IO for live streaming updates.',
      github: 'https://github.com/Rishi-0904',
      demo: '#',
      tech: [
        'LangGraph', 'MCP', 'RabbitMQ', 'Socket.IO', 'Docker',
        'FastAPI', 'React', 'Multi-Agent',
      ],
      architecture: {
        nodes: [
          { id: 'user', label: 'User', desc: 'Inputs destination, dates, and budget preferences.' },
          { id: 'orchestrator', label: 'Orchestrator', desc: 'LangGraph orchestrator breaks the travel query into sub-tasks and delegates via RabbitMQ.' },
          { id: 'travel', label: 'Travel Agent', desc: 'Plans itinerary and suggests attractions, cultural experiences, and logistics.' },
          { id: 'weather', label: 'Weather Agent', desc: 'Fetches real-time weather forecasts and alerts for the destination.' },
          { id: 'budget', label: 'Budget Agent', desc: 'Estimates and optimizes costs across accommodation, transport, and activities.' },
          { id: 'route', label: 'Route Agent', desc: 'Plans optimal routes between locations using mapping APIs.' },
          { id: 'itinerary', label: 'Final Itinerary', desc: 'Aggregated, validated travel plan streamed to the user via Socket.IO.' },
        ],
        edges: [
          ['user', 'orchestrator'],
          ['orchestrator', 'travel'],
          ['orchestrator', 'weather'],
          ['orchestrator', 'budget'],
          ['orchestrator', 'route'],
          ['travel', 'itinerary'],
          ['weather', 'itinerary'],
          ['budget', 'itinerary'],
          ['route', 'itinerary'],
        ],
      },
    },
    {
      id: 'autonomous-driving',
      name: 'Autonomous Driving Simulator',
      tagline: 'Self-Driving Vehicle Perception & Planning System',
      status: 'active',
      description:
        'An autonomous driving simulation system implementing full AV pipeline: multi-sensor fusion (Camera, LiDAR, GPS, IMU), real-time perception (object & lane detection), trajectory prediction, path planning with A*, and PID control.',
      github: 'https://github.com/Rishi-0904',
      demo: '#',
      tech: [
        'Computer Vision', 'Sensor Fusion', 'PyTorch', 'YOLO',
        'A* Algorithm', 'PID Control', 'Python', 'OpenCV',
      ],
      pipeline: [
        { id: 'camera', label: 'Camera', icon: '📷', desc: 'High-resolution RGB input for visual scene understanding.' },
        { id: 'lidar', label: 'LiDAR', icon: '🔴', desc: '3D point cloud data for precise depth and obstacle mapping.' },
        { id: 'gps', label: 'GPS', icon: '🛰', desc: 'Global positioning for route planning and localization.' },
        { id: 'imu', label: 'IMU', icon: '🧭', desc: 'Inertial measurement for vehicle dynamics and orientation.' },
        { id: 'perception', label: 'Perception', icon: '👁', desc: 'Object detection (YOLO), lane detection, semantic segmentation, sensor fusion.' },
        { id: 'prediction', label: 'Prediction', icon: '🔮', desc: 'Trajectory prediction for detected agents using motion models.' },
        { id: 'planning', label: 'Planning', icon: '🗺', desc: 'A* path planning with obstacle avoidance and route optimization.' },
        { id: 'control', label: 'Control', icon: '🎮', desc: 'PID controller translates plan to steering, throttle, and brake commands.' },
      ],
    },
  ],
  achievements: [
    {
      id: 'fitfusion',
      title: 'FitFusion — 1st Runner-Up',
      event: 'IIT Roorkee Hackathon',
      year: '2024',
      desc: 'Built an AI-powered fitness platform with computer vision-based form correction and personalized workout planning. Achieved 1st Runner-Up among 200+ teams.',
      icon: '🏆',
      color: 'var(--amber)',
    },
    {
      id: 'hack36',
      title: 'Hack36 — Top 25 Finalist',
      event: 'MNNIT Allahabad National Hackathon',
      year: '2024',
      desc: 'Selected as Top 25 finalist in Hack36, MNNIT\'s national-level hackathon with 1000+ participants from premier engineering colleges.',
      icon: '🥈',
      color: 'var(--cyan)',
    },
    {
      id: 'softathalon',
      title: 'Softathalon Finalist',
      event: 'Technical Fest',
      year: '2023',
      desc: 'Finalist in the Softathalon programming event, demonstrating strong algorithmic problem-solving skills under time constraints.',
      icon: '⚡',
      color: 'var(--purple)',
    },
    {
      id: 'codeforces',
      title: 'Codeforces Pupil',
      event: 'Competitive Programming',
      year: '2023–Present',
      desc: 'Active Codeforces competitive programmer with consistent rating improvements, solving problems across dynamic programming, graphs, and data structures.',
      icon: '🔵',
      color: 'var(--blue)',
    },
    {
      id: 'leetcode',
      title: 'LeetCode Knight',
      event: 'Algorithm Platform',
      year: '2023–Present',
      desc: 'Achieved Knight rank on LeetCode (top 5%), with 500+ problems solved across all difficulty levels. Specialization in dynamic programming and graph algorithms.',
      icon: '⚔️',
      color: 'var(--amber)',
    },
  ],
} as const;

export type Project = typeof PORTFOLIO_DATA.projects[number];
export type Achievement = typeof PORTFOLIO_DATA.achievements[number];
export type Skill = { name: string; level: number };
